const enc = new TextEncoder();
const now = () => Date.now();
const json = (data,status=200) => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
async function sha256(v){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function randomCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const b=crypto.getRandomValues(new Uint8Array(8));let s='';for(const x of b)s+=a[x%a.length];return s.slice(0,4)+'-'+s.slice(4);}
async function session(env,codeId,deviceId,expiresAt){const raw=crypto.randomUUID()+crypto.randomUUID();const hash=await sha256(raw);await env.DB.prepare('INSERT INTO sessions(code_id,device_id,session_hash,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?,?)').bind(codeId,deviceId,hash,now(),expiresAt,now()).run();return raw;}
async function auth(request,env){const raw=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!raw)return null;const hash=await sha256(raw);const r=await env.DB.prepare('SELECT s.*,c.status AS code_status,c.expires_at AS code_expires_at FROM sessions s JOIN codes c ON c.id=s.code_id WHERE s.session_hash=? LIMIT 1').bind(hash).first();if(!r||r.code_status==='revoked'||r.expires_at<now()||(r.code_expires_at&&r.code_expires_at<now()))return null;await env.DB.prepare('UPDATE sessions SET last_seen_at=? WHERE id=?').bind(now(),r.id).run();await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),r.device_id).run();return r;}
const adminOk=(req,env)=>(env.ADMIN_TOKEN||'')===(req.headers.get('x-admin-token')||'') && !!env.ADMIN_TOKEN;
async function verify(req,env){const b=await req.json().catch(()=>null);const code=String(b?.code||'').trim().toUpperCase();const dt=String(b?.deviceToken||'').trim();if(!/^[A-Z0-9]{4}-[A-Z0-9]{4}$/.test(code)||dt.length<16)return json({ok:false,error:'验证码或设备信息无效。'},400);const ch=await sha256(code);const c=await env.DB.prepare('SELECT * FROM codes WHERE code_hash=? LIMIT 1').bind(ch).first();if(!c)return json({ok:false,error:'验证码不存在。'},404);if(c.status==='revoked')return json({ok:false,error:'这个验证码已经失效。'},403);let exp=c.expires_at;if(!c.activated_at){exp=now()+48*3600000;await env.DB.prepare("UPDATE codes SET status='active',activated_at=?,expires_at=? WHERE id=?").bind(now(),exp,c.id).run();}else if(exp<now()){await env.DB.prepare("UPDATE codes SET status='expired' WHERE id=?").bind(c.id).run();return json({ok:false,error:'这个验证码已经过期。'},403);}const dh=await sha256(dt);let d=await env.DB.prepare('SELECT * FROM devices WHERE code_id=? AND device_token_hash=? LIMIT 1').bind(c.id,dh).first();if(!d){const n=await env.DB.prepare('SELECT COUNT(*) AS count FROM devices WHERE code_id=?').bind(c.id).first();if((n?.count||0)>=c.max_devices)return json({ok:false,error:`这个验证码已经绑定 ${c.max_devices} 台设备，无法继续绑定新设备。`},403);const r=await env.DB.prepare('INSERT INTO devices(code_id,device_token_hash,user_agent,created_at,last_seen_at) VALUES(?,?,?,?,?)').bind(c.id,dh,req.headers.get('user-agent')||'',now(),now()).run();d={id:r.meta.last_row_id};}else await env.DB.prepare('UPDATE devices SET last_seen_at=?,user_agent=? WHERE id=?').bind(now(),req.headers.get('user-agent')||'',d.id).run();const token=await session(env,c.id,d.id,exp);const n=await env.DB.prepare('SELECT COUNT(*) AS count FROM devices WHERE code_id=?').bind(c.id).first();return json({ok:true,token,expiresAt:exp,devicesUsed:n?.count||1,devicesMax:c.max_devices});}
async function api(req,env,path){
 if(req.method==='POST'&&path==='/api/verify')return verify(req,env);
 if(req.method==='GET'&&path==='/api/me'){const s=await auth(req,env);if(!s)return json({ok:false,error:'授权已失效，请重新输入验证码。'},401);const t=await env.DB.prepare('SELECT slug,title,subtitle,description,enabled FROM tests WHERE enabled=1 ORDER BY sort_order,id').all();const d=await env.DB.prepare('SELECT id,created_at,last_seen_at,user_agent FROM devices WHERE code_id=? ORDER BY id').bind(s.code_id).all();return json({ok:true,expiresAt:s.expires_at,tests:t.results||[],devices:d.results||[]});}
 if(path==='/api/admin/codes'){if(!adminOk(req,env))return json({ok:false,error:'管理员权限不足。'},401);if(req.method==='GET'){const r=await env.DB.prepare('SELECT c.*,(SELECT COUNT(*) FROM devices d WHERE d.code_id=c.id) AS device_count FROM codes c ORDER BY c.id DESC LIMIT 200').all();return json({ok:true,codes:r.results||[]});}if(req.method==='POST'){const b=await req.json().catch(()=>({}));const q=Math.max(1,Math.min(50,Number(b?.quantity||1)));const note=String(b?.note||'').slice(0,200);const out=[];for(let i=0;i<q;i++){let code,hash,exists=true;while(exists){code=randomCode();hash=await sha256(code);exists=!!(await env.DB.prepare('SELECT id FROM codes WHERE code_hash=?').bind(hash).first());}await env.DB.prepare("INSERT INTO codes(code_hash,code_preview,status,created_at,max_devices,note) VALUES(?,?, 'unused', ?,5,?)").bind(hash,code,now(),note).run();out.push(code);}return json({ok:true,codes:out});}}
 const rv=path.match(/^\/api\/admin\/codes\/(\d+)\/revoke$/);if(req.method==='POST'&&rv){if(!adminOk(req,env))return json({ok:false,error:'管理员权限不足。'},401);await env.DB.prepare("UPDATE codes SET status='revoked' WHERE id=?").bind(+rv[1]).run();return json({ok:true});}
 const ex=path.match(/^\/api\/admin\/codes\/(\d+)\/extend$/);if(req.method==='POST'&&ex){if(!adminOk(req,env))return json({ok:false,error:'管理员权限不足。'},401);const h=Math.max(1,Math.min(168,Number((await req.json().catch(()=>({})))?.hours||48)));await env.DB.prepare("UPDATE codes SET expires_at=CASE WHEN expires_at IS NULL OR expires_at<? THEN ? ELSE expires_at+? END,status='active' WHERE id=?").bind(now(),now()+h*3600000,h*3600000,+ex[1]).run();return json({ok:true});}
 const ds=path.match(/^\/api\/admin\/codes\/(\d+)\/devices$/);if(req.method==='GET'&&ds){if(!adminOk(req,env))return json({ok:false,error:'管理员权限不足。'},401);const r=await env.DB.prepare('SELECT id,created_at,last_seen_at,user_agent FROM devices WHERE code_id=? ORDER BY id').bind(+ds[1]).all();return json({ok:true,devices:r.results||[]});}
 const dd=path.match(/^\/api\/admin\/devices\/(\d+)$/);if(req.method==='DELETE'&&dd){if(!adminOk(req,env))return json({ok:false,error:'管理员权限不足。'},401);await env.DB.prepare('DELETE FROM devices WHERE id=?').bind(+dd[1]).run();return json({ok:true});}
 return json({ok:false,error:'Not found'},404);
}
export default {async fetch(req,env){const u=new URL(req.url);if(u.pathname.startsWith('/api/'))return api(req,env,u.pathname);if(u.pathname.startsWith('/test/'))return env.ASSETS.fetch(new Request(new URL('/test-placeholder.html',req.url),req));return env.ASSETS.fetch(req);}};
